/*
NOTE: AI Autogenerated Mock Test Cases
JetBrains AI Assist using Claud 4.5 Opus prompt:
Using pullrequest_mock.go and repository_mock_tests.go as examples, generate Gomock mock test cases for the following
issues functions; Gets, Get, Create, Update, Delete.
*/

package mock_tests

import (
	"errors"
	"testing"

	go_bitbucket "github.com/ktrysmt/go-bitbucket"
	"github.com/ktrysmt/go-bitbucket/mockgen"
	"github.com/stretchr/testify/assert"
	"go.uber.org/mock/gomock"
)

func TestMockIssues_Gets_Success(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
	}

	expectedIssue := map[string]interface{}{
		"id":    1,
		"title": "Test Issue",
		"state": "open",
	}
	expectedIssuesList := []interface{}{expectedIssue}

	mockIssuesInst.EXPECT().
		Gets(inIssuesOpts).
		Times(1).
		Return(expectedIssuesList, nil)

	actualIssuesList, actualErr := mockIssuesInst.Gets(inIssuesOpts)

	assert.Nilf(t, actualErr, "No error should have been returned, but got: %v", actualErr)
	assert.NotNil(t, actualIssuesList, "Issues list should be returned.")
	assert.Equal(t, expectedIssuesList, actualIssuesList, "Actual and Expected issues lists should be equal.")
}

func TestMockIssues_Gets_Error(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)
	expectedMockError := errors.New("Not Found")

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test?::=workspace",
		RepoSlug: "test-repo",
	}

	mockIssuesInst.EXPECT().
		Gets(inIssuesOpts).
		Times(1).
		Return(nil, expectedMockError)

	actualIssuesList, actualErr := mockIssuesInst.Gets(inIssuesOpts)

	assert.NotNil(t, actualErr)
	assert.Nilf(t, actualIssuesList, "The returned list of issues should be nil, but got: %v", actualIssuesList)
	assert.Equal(t, expectedMockError.Error(), actualErr.Error())
}

func TestMockIssues_Get_Success(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		ID:       "1",
	}

	expectedIssue := map[string]interface{}{
		"id":    1,
		"title": "Test Issue",
		"state": "open",
	}

	mockIssuesInst.EXPECT().
		Get(inIssuesOpts).
		Times(1).
		Return(expectedIssue, nil)

	actualIssue, actualErr := mockIssuesInst.Get(inIssuesOpts)

	assert.Nilf(t, actualErr, "No error should have been returned, but got: %v", actualErr)
	assert.NotNil(t, actualIssue, "Issue should be returned.")
	assert.Equal(t, expectedIssue, actualIssue, "Actual and Expected issues should be equal.")
}

func TestMockIssues_Get_Error(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)
	expectedMockError := errors.New("Not Found")

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		ID:       "999",
	}

	mockIssuesInst.EXPECT().
		Get(inIssuesOpts).
		Times(1).
		Return(nil, expectedMockError)

	actualIssue, actualErr := mockIssuesInst.Get(inIssuesOpts)

	assert.NotNil(t, actualErr)
	assert.Nilf(t, actualIssue, "The returned issue should be nil, but got: %v", actualIssue)
	assert.Equal(t, expectedMockError.Error(), actualErr.Error())
}

func TestMockIssues_Create_Success(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		Title:    "New Test Issue",
		Content:  "This is a test issue description",
		Kind:     "bug",
		Priority: "major",
	}

	expectedIssue := map[string]interface{}{
		"id":       1,
		"title":    "New Test Issue",
		"state":    "new",
		"kind":     "bug",
		"priority": "major",
	}

	mockIssuesInst.EXPECT().
		Create(inIssuesOpts).
		Times(1).
		Return(expectedIssue, nil)

	actualIssue, actualErr := mockIssuesInst.Create(inIssuesOpts)

	assert.Nilf(t, actualErr, "No error should have been returned, but got: %v", actualErr)
	assert.NotNil(t, actualIssue, "Created issue should be returned.")
	assert.Equal(t, expectedIssue, actualIssue, "Actual and Expected issues should be equal.")
}

func TestMockIssues_Create_Error(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)
	expectedMockError := errors.New("Bad Request")

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		// Missing required Title field
	}

	mockIssuesInst.EXPECT().
		Create(inIssuesOpts).
		Times(1).
		Return(nil, expectedMockError)

	actualIssue, actualErr := mockIssuesInst.Create(inIssuesOpts)

	assert.NotNil(t, actualErr)
	assert.Nilf(t, actualIssue, "The returned issue should be nil, but got: %v", actualIssue)
	assert.Equal(t, expectedMockError.Error(), actualErr.Error())
}

func TestMockIssues_Update_Success(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		ID:       "1",
		Title:    "Updated Test Issue",
		State:    "open",
		Priority: "critical",
	}

	expectedUpdatedIssue := map[string]interface{}{
		"id":       1,
		"title":    "Updated Test Issue",
		"state":    "open",
		"priority": "critical",
	}

	mockIssuesInst.EXPECT().
		Update(inIssuesOpts).
		Times(1).
		Return(expectedUpdatedIssue, nil)

	actualUpdatedIssue, actualErr := mockIssuesInst.Update(inIssuesOpts)

	assert.Nilf(t, actualErr, "No error should have been returned, but got: %v", actualErr)
	assert.NotNil(t, actualUpdatedIssue, "Updated issue should be returned.")
	assert.Equal(t, expectedUpdatedIssue, actualUpdatedIssue, "Actual and Expected updated issues should be equal.")
}

func TestMockIssues_Update_Error(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)
	expectedMockError := errors.New("Not Found")

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		ID:       "999",
		Title:    "Updated Test Issue",
	}

	mockIssuesInst.EXPECT().
		Update(inIssuesOpts).
		Times(1).
		Return(nil, expectedMockError)

	actualUpdatedIssue, actualErr := mockIssuesInst.Update(inIssuesOpts)

	assert.NotNil(t, actualErr)
	assert.Nilf(t, actualUpdatedIssue, "The returned updated issue should be nil, but got: %v", actualUpdatedIssue)
	assert.Equal(t, expectedMockError.Error(), actualErr.Error())
}

func TestMockIssues_Delete_Success(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		ID:       "1",
	}

	mockIssuesInst.EXPECT().
		Delete(inIssuesOpts).
		Times(1).
		Return(nil, nil)

	actualResult, actualErr := mockIssuesInst.Delete(inIssuesOpts)

	assert.Nilf(t, actualErr, "No error should have been returned, but got: %v", actualErr)
	assert.Nil(t, actualResult, "Delete should return nil on success.")
}

func TestMockIssues_Delete_Error(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockIssuesInst := mockgen.NewMockissues(ctrl)
	expectedMockError := errors.New("Not Found")

	inIssuesOpts := &go_bitbucket.IssuesOptions{
		Owner:    "test-workspace",
		RepoSlug: "test-repo",
		ID:       "999",
	}

	mockIssuesInst.EXPECT().
		Delete(inIssuesOpts).
		Times(1).
		Return(nil, expectedMockError)

	actualResult, actualErr := mockIssuesInst.Delete(inIssuesOpts)

	assert.NotNil(t, actualErr)
	assert.Nilf(t, actualResult, "The returned result should be nil, but got: %v", actualResult)
	assert.Equal(t, expectedMockError.Error(), actualErr.Error())
}
