// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.go
//
// Generated by this command:
//
//	mockgen -source=bitbucket.go -destination=mockgen/bitbucket_mockgen.go -package=mockgen
//

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	bitbucket "github.com/ktrysmt/go-bitbucket"
	gomock "go.uber.org/mock/gomock"
)

// Mockusers is a mock of users interface.
type Mockusers struct {
	ctrl     *gomock.Controller
	recorder *MockusersMockRecorder
	isgomock struct{}
}

// MockusersMockRecorder is the mock recorder for Mockusers.
type MockusersMockRecorder struct {
	mock *Mockusers
}

// NewMockusers creates a new mock instance.
func NewMockusers(ctrl *gomock.Controller) *Mockusers {
	mock := &Mockusers{ctrl: ctrl}
	mock.recorder = &MockusersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockusers) EXPECT() *MockusersMockRecorder {
	return m.recorder
}

// Followers mocks base method.
func (m *Mockusers) Followers(username string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Followers", username)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Followers indicates an expected call of Followers.
func (mr *MockusersMockRecorder) Followers(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Followers", reflect.TypeOf((*Mockusers)(nil).Followers), username)
}

// Following mocks base method.
func (m *Mockusers) Following(username string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Following", username)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Following indicates an expected call of Following.
func (mr *MockusersMockRecorder) Following(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Following", reflect.TypeOf((*Mockusers)(nil).Following), username)
}

// Get mocks base method.
func (m *Mockusers) Get(username string) (*bitbucket.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", username)
	ret0, _ := ret[0].(*bitbucket.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockusersMockRecorder) Get(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockusers)(nil).Get), username)
}

// Repositories mocks base method.
func (m *Mockusers) Repositories(username string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repositories", username)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repositories indicates an expected call of Repositories.
func (mr *MockusersMockRecorder) Repositories(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repositories", reflect.TypeOf((*Mockusers)(nil).Repositories), username)
}

// Mockuser is a mock of user interface.
type Mockuser struct {
	ctrl     *gomock.Controller
	recorder *MockuserMockRecorder
	isgomock struct{}
}

// MockuserMockRecorder is the mock recorder for Mockuser.
type MockuserMockRecorder struct {
	mock *Mockuser
}

// NewMockuser creates a new mock instance.
func NewMockuser(ctrl *gomock.Controller) *Mockuser {
	mock := &Mockuser{ctrl: ctrl}
	mock.recorder = &MockuserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser) EXPECT() *MockuserMockRecorder {
	return m.recorder
}

// Emails mocks base method.
func (m *Mockuser) Emails() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emails")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Emails indicates an expected call of Emails.
func (mr *MockuserMockRecorder) Emails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emails", reflect.TypeOf((*Mockuser)(nil).Emails))
}

// Profile mocks base method.
func (m *Mockuser) Profile() (*bitbucket.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(*bitbucket.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockuserMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*Mockuser)(nil).Profile))
}

// Mockpullrequests is a mock of pullrequests interface.
type Mockpullrequests struct {
	ctrl     *gomock.Controller
	recorder *MockpullrequestsMockRecorder
	isgomock struct{}
}

// MockpullrequestsMockRecorder is the mock recorder for Mockpullrequests.
type MockpullrequestsMockRecorder struct {
	mock *Mockpullrequests
}

// NewMockpullrequests creates a new mock instance.
func NewMockpullrequests(ctrl *gomock.Controller) *Mockpullrequests {
	mock := &Mockpullrequests{ctrl: ctrl}
	mock.recorder = &MockpullrequestsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpullrequests) EXPECT() *MockpullrequestsMockRecorder {
	return m.recorder
}

// Activities mocks base method.
func (m *Mockpullrequests) Activities(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activities", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activities indicates an expected call of Activities.
func (mr *MockpullrequestsMockRecorder) Activities(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activities", reflect.TypeOf((*Mockpullrequests)(nil).Activities), opt)
}

// Activity mocks base method.
func (m *Mockpullrequests) Activity(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activity", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activity indicates an expected call of Activity.
func (mr *MockpullrequestsMockRecorder) Activity(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activity", reflect.TypeOf((*Mockpullrequests)(nil).Activity), opt)
}

// Commits mocks base method.
func (m *Mockpullrequests) Commits(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commits", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commits indicates an expected call of Commits.
func (mr *MockpullrequestsMockRecorder) Commits(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commits", reflect.TypeOf((*Mockpullrequests)(nil).Commits), opt)
}

// Create mocks base method.
func (m *Mockpullrequests) Create(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockpullrequestsMockRecorder) Create(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockpullrequests)(nil).Create), opt)
}

// Decline mocks base method.
func (m *Mockpullrequests) Decline(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decline", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decline indicates an expected call of Decline.
func (mr *MockpullrequestsMockRecorder) Decline(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decline", reflect.TypeOf((*Mockpullrequests)(nil).Decline), opt)
}

// Diff mocks base method.
func (m *Mockpullrequests) Diff(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Diff", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Diff indicates an expected call of Diff.
func (mr *MockpullrequestsMockRecorder) Diff(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Diff", reflect.TypeOf((*Mockpullrequests)(nil).Diff), opt)
}

// Get mocks base method.
func (m *Mockpullrequests) Get(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockpullrequestsMockRecorder) Get(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockpullrequests)(nil).Get), opt)
}

// List mocks base method.
func (m *Mockpullrequests) List(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockpullrequestsMockRecorder) List(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockpullrequests)(nil).List), opt)
}

// Merge mocks base method.
func (m *Mockpullrequests) Merge(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge indicates an expected call of Merge.
func (mr *MockpullrequestsMockRecorder) Merge(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*Mockpullrequests)(nil).Merge), opt)
}

// Patch mocks base method.
func (m *Mockpullrequests) Patch(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockpullrequestsMockRecorder) Patch(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*Mockpullrequests)(nil).Patch), opt)
}

// Update mocks base method.
func (m *Mockpullrequests) Update(opt bitbucket.PullRequestsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockpullrequestsMockRecorder) Update(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockpullrequests)(nil).Update), opt)
}

// Mockworkspace is a mock of workspace interface.
type Mockworkspace struct {
	ctrl     *gomock.Controller
	recorder *MockworkspaceMockRecorder
	isgomock struct{}
}

// MockworkspaceMockRecorder is the mock recorder for Mockworkspace.
type MockworkspaceMockRecorder struct {
	mock *Mockworkspace
}

// NewMockworkspace creates a new mock instance.
func NewMockworkspace(ctrl *gomock.Controller) *Mockworkspace {
	mock := &Mockworkspace{ctrl: ctrl}
	mock.recorder = &MockworkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockworkspace) EXPECT() *MockworkspaceMockRecorder {
	return m.recorder
}

// CreateProject mocks base method.
func (m *Mockworkspace) CreateProject(opt bitbucket.ProjectOptions) (*bitbucket.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", opt)
	ret0, _ := ret[0].(*bitbucket.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockworkspaceMockRecorder) CreateProject(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*Mockworkspace)(nil).CreateProject), opt)
}

// GetProject mocks base method.
func (m *Mockworkspace) GetProject(opt bitbucket.ProjectOptions) (*bitbucket.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", opt)
	ret0, _ := ret[0].(*bitbucket.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockworkspaceMockRecorder) GetProject(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*Mockworkspace)(nil).GetProject), opt)
}

// Mockissues is a mock of issues interface.
type Mockissues struct {
	ctrl     *gomock.Controller
	recorder *MockissuesMockRecorder
	isgomock struct{}
}

// MockissuesMockRecorder is the mock recorder for Mockissues.
type MockissuesMockRecorder struct {
	mock *Mockissues
}

// NewMockissues creates a new mock instance.
func NewMockissues(ctrl *gomock.Controller) *Mockissues {
	mock := &Mockissues{ctrl: ctrl}
	mock.recorder = &MockissuesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockissues) EXPECT() *MockissuesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockissues) Create(io *bitbucket.IssuesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", io)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockissuesMockRecorder) Create(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockissues)(nil).Create), io)
}

// CreateChange mocks base method.
func (m *Mockissues) CreateChange(ico *bitbucket.IssueChangesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChange", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChange indicates an expected call of CreateChange.
func (mr *MockissuesMockRecorder) CreateChange(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChange", reflect.TypeOf((*Mockissues)(nil).CreateChange), ico)
}

// CreateComment mocks base method.
func (m *Mockissues) CreateComment(ico *bitbucket.IssueCommentsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockissuesMockRecorder) CreateComment(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*Mockissues)(nil).CreateComment), ico)
}

// Delete mocks base method.
func (m *Mockissues) Delete(io *bitbucket.IssuesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", io)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockissuesMockRecorder) Delete(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockissues)(nil).Delete), io)
}

// DeleteComment mocks base method.
func (m *Mockissues) DeleteComment(ico *bitbucket.IssueCommentsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockissuesMockRecorder) DeleteComment(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*Mockissues)(nil).DeleteComment), ico)
}

// DeleteVote mocks base method.
func (m *Mockissues) DeleteVote(io *bitbucket.IssuesOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVote", io)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVote indicates an expected call of DeleteVote.
func (mr *MockissuesMockRecorder) DeleteVote(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVote", reflect.TypeOf((*Mockissues)(nil).DeleteVote), io)
}

// DeleteWatch mocks base method.
func (m *Mockissues) DeleteWatch(io *bitbucket.IssuesOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWatch", io)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWatch indicates an expected call of DeleteWatch.
func (mr *MockissuesMockRecorder) DeleteWatch(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWatch", reflect.TypeOf((*Mockissues)(nil).DeleteWatch), io)
}

// Get mocks base method.
func (m *Mockissues) Get(io *bitbucket.IssuesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", io)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockissuesMockRecorder) Get(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockissues)(nil).Get), io)
}

// GetChange mocks base method.
func (m *Mockissues) GetChange(ico *bitbucket.IssueChangesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChange", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChange indicates an expected call of GetChange.
func (mr *MockissuesMockRecorder) GetChange(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChange", reflect.TypeOf((*Mockissues)(nil).GetChange), ico)
}

// GetChanges mocks base method.
func (m *Mockissues) GetChanges(ico *bitbucket.IssueChangesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChanges", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChanges indicates an expected call of GetChanges.
func (mr *MockissuesMockRecorder) GetChanges(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChanges", reflect.TypeOf((*Mockissues)(nil).GetChanges), ico)
}

// GetComment mocks base method.
func (m *Mockissues) GetComment(ico *bitbucket.IssueCommentsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockissuesMockRecorder) GetComment(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*Mockissues)(nil).GetComment), ico)
}

// GetComments mocks base method.
func (m *Mockissues) GetComments(ico *bitbucket.IssueCommentsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockissuesMockRecorder) GetComments(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*Mockissues)(nil).GetComments), ico)
}

// GetVote mocks base method.
func (m *Mockissues) GetVote(io *bitbucket.IssuesOptions) (bool, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVote", io)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVote indicates an expected call of GetVote.
func (mr *MockissuesMockRecorder) GetVote(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVote", reflect.TypeOf((*Mockissues)(nil).GetVote), io)
}

// GetWatch mocks base method.
func (m *Mockissues) GetWatch(io *bitbucket.IssuesOptions) (bool, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatch", io)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWatch indicates an expected call of GetWatch.
func (mr *MockissuesMockRecorder) GetWatch(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatch", reflect.TypeOf((*Mockissues)(nil).GetWatch), io)
}

// Gets mocks base method.
func (m *Mockissues) Gets(io *bitbucket.IssuesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gets", io)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gets indicates an expected call of Gets.
func (mr *MockissuesMockRecorder) Gets(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gets", reflect.TypeOf((*Mockissues)(nil).Gets), io)
}

// PutVote mocks base method.
func (m *Mockissues) PutVote(io *bitbucket.IssuesOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVote", io)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutVote indicates an expected call of PutVote.
func (mr *MockissuesMockRecorder) PutVote(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVote", reflect.TypeOf((*Mockissues)(nil).PutVote), io)
}

// PutWatch mocks base method.
func (m *Mockissues) PutWatch(io *bitbucket.IssuesOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutWatch", io)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutWatch indicates an expected call of PutWatch.
func (mr *MockissuesMockRecorder) PutWatch(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutWatch", reflect.TypeOf((*Mockissues)(nil).PutWatch), io)
}

// Update mocks base method.
func (m *Mockissues) Update(io *bitbucket.IssuesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", io)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockissuesMockRecorder) Update(io any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockissues)(nil).Update), io)
}

// UpdateComment mocks base method.
func (m *Mockissues) UpdateComment(ico *bitbucket.IssueCommentsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ico)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockissuesMockRecorder) UpdateComment(ico any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*Mockissues)(nil).UpdateComment), ico)
}

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// AddDefaultReviewer mocks base method.
func (m *Mockrepository) AddDefaultReviewer(opt bitbucket.RepositoryDefaultReviewerOptions) (*bitbucket.DefaultReviewer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDefaultReviewer", opt)
	ret0, _ := ret[0].(*bitbucket.DefaultReviewer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDefaultReviewer indicates an expected call of AddDefaultReviewer.
func (mr *MockrepositoryMockRecorder) AddDefaultReviewer(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDefaultReviewer", reflect.TypeOf((*Mockrepository)(nil).AddDefaultReviewer), opt)
}

// AddDeploymentVariable mocks base method.
func (m *Mockrepository) AddDeploymentVariable(opt bitbucket.RepositoryDeploymentVariableOptions) (*bitbucket.DeploymentVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeploymentVariable", opt)
	ret0, _ := ret[0].(*bitbucket.DeploymentVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDeploymentVariable indicates an expected call of AddDeploymentVariable.
func (mr *MockrepositoryMockRecorder) AddDeploymentVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeploymentVariable", reflect.TypeOf((*Mockrepository)(nil).AddDeploymentVariable), opt)
}

// AddEnvironment mocks base method.
func (m *Mockrepository) AddEnvironment(opt bitbucket.RepositoryEnvironmentOptions) (*bitbucket.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEnvironment", opt)
	ret0, _ := ret[0].(*bitbucket.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddEnvironment indicates an expected call of AddEnvironment.
func (mr *MockrepositoryMockRecorder) AddEnvironment(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEnvironment", reflect.TypeOf((*Mockrepository)(nil).AddEnvironment), opt)
}

// AddPipelineKeyPair mocks base method.
func (m *Mockrepository) AddPipelineKeyPair(opt bitbucket.RepositoryPipelineKeyPairOptions) (*bitbucket.PipelineKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPipelineKeyPair", opt)
	ret0, _ := ret[0].(*bitbucket.PipelineKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPipelineKeyPair indicates an expected call of AddPipelineKeyPair.
func (mr *MockrepositoryMockRecorder) AddPipelineKeyPair(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPipelineKeyPair", reflect.TypeOf((*Mockrepository)(nil).AddPipelineKeyPair), opt)
}

// AddPipelineVariable mocks base method.
func (m *Mockrepository) AddPipelineVariable(opt bitbucket.RepositoryPipelineVariableOptions) (*bitbucket.PipelineVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPipelineVariable", opt)
	ret0, _ := ret[0].(*bitbucket.PipelineVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPipelineVariable indicates an expected call of AddPipelineVariable.
func (mr *MockrepositoryMockRecorder) AddPipelineVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPipelineVariable", reflect.TypeOf((*Mockrepository)(nil).AddPipelineVariable), opt)
}

// BranchingModel mocks base method.
func (m *Mockrepository) BranchingModel(opt bitbucket.RepositoryBranchingModelOptions) (*bitbucket.BranchingModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BranchingModel", opt)
	ret0, _ := ret[0].(*bitbucket.BranchingModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BranchingModel indicates an expected call of BranchingModel.
func (mr *MockrepositoryMockRecorder) BranchingModel(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BranchingModel", reflect.TypeOf((*Mockrepository)(nil).BranchingModel), opt)
}

// Create mocks base method.
func (m *Mockrepository) Create(opt bitbucket.RepositoryOptions) (*bitbucket.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", opt)
	ret0, _ := ret[0].(*bitbucket.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockrepositoryMockRecorder) Create(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockrepository)(nil).Create), opt)
}

// Delete mocks base method.
func (m *Mockrepository) Delete(opt bitbucket.RepositoryOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockrepositoryMockRecorder) Delete(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockrepository)(nil).Delete), opt)
}

// DeleteDefaultReviewer mocks base method.
func (m *Mockrepository) DeleteDefaultReviewer(opt bitbucket.RepositoryDefaultReviewerOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDefaultReviewer", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDefaultReviewer indicates an expected call of DeleteDefaultReviewer.
func (mr *MockrepositoryMockRecorder) DeleteDefaultReviewer(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDefaultReviewer", reflect.TypeOf((*Mockrepository)(nil).DeleteDefaultReviewer), opt)
}

// DeleteDeploymentVariable mocks base method.
func (m *Mockrepository) DeleteDeploymentVariable(opt bitbucket.RepositoryDeploymentVariableDeleteOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeploymentVariable", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDeploymentVariable indicates an expected call of DeleteDeploymentVariable.
func (mr *MockrepositoryMockRecorder) DeleteDeploymentVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeploymentVariable", reflect.TypeOf((*Mockrepository)(nil).DeleteDeploymentVariable), opt)
}

// DeleteEnvironment mocks base method.
func (m *Mockrepository) DeleteEnvironment(opt bitbucket.RepositoryEnvironmentDeleteOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironment", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEnvironment indicates an expected call of DeleteEnvironment.
func (mr *MockrepositoryMockRecorder) DeleteEnvironment(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironment", reflect.TypeOf((*Mockrepository)(nil).DeleteEnvironment), opt)
}

// DeletePipelineVariable mocks base method.
func (m *Mockrepository) DeletePipelineVariable(opt bitbucket.RepositoryPipelineVariableDeleteOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePipelineVariable", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePipelineVariable indicates an expected call of DeletePipelineVariable.
func (mr *MockrepositoryMockRecorder) DeletePipelineVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePipelineVariable", reflect.TypeOf((*Mockrepository)(nil).DeletePipelineVariable), opt)
}

// Get mocks base method.
func (m *Mockrepository) Get(opt bitbucket.RepositoryOptions) (*bitbucket.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", opt)
	ret0, _ := ret[0].(*bitbucket.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockrepositoryMockRecorder) Get(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockrepository)(nil).Get), opt)
}

// GetDefaultReviewer mocks base method.
func (m *Mockrepository) GetDefaultReviewer(opt bitbucket.RepositoryDefaultReviewerOptions) (*bitbucket.DefaultReviewer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultReviewer", opt)
	ret0, _ := ret[0].(*bitbucket.DefaultReviewer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultReviewer indicates an expected call of GetDefaultReviewer.
func (mr *MockrepositoryMockRecorder) GetDefaultReviewer(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultReviewer", reflect.TypeOf((*Mockrepository)(nil).GetDefaultReviewer), opt)
}

// GetEnvironment mocks base method.
func (m *Mockrepository) GetEnvironment(opt bitbucket.RepositoryEnvironmentOptions) (*bitbucket.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", opt)
	ret0, _ := ret[0].(*bitbucket.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment.
func (mr *MockrepositoryMockRecorder) GetEnvironment(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*Mockrepository)(nil).GetEnvironment), opt)
}

// GetFileBlob mocks base method.
func (m *Mockrepository) GetFileBlob(opt bitbucket.RepositoryBlobOptions) (*bitbucket.RepositoryBlob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileBlob", opt)
	ret0, _ := ret[0].(*bitbucket.RepositoryBlob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileBlob indicates an expected call of GetFileBlob.
func (mr *MockrepositoryMockRecorder) GetFileBlob(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileBlob", reflect.TypeOf((*Mockrepository)(nil).GetFileBlob), opt)
}

// GetPipelineVariable mocks base method.
func (m *Mockrepository) GetPipelineVariable(opt bitbucket.RepositoryPipelineVariableOptions) (*bitbucket.PipelineVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineVariable", opt)
	ret0, _ := ret[0].(*bitbucket.PipelineVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineVariable indicates an expected call of GetPipelineVariable.
func (mr *MockrepositoryMockRecorder) GetPipelineVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineVariable", reflect.TypeOf((*Mockrepository)(nil).GetPipelineVariable), opt)
}

// ListBranches mocks base method.
func (m *Mockrepository) ListBranches(opt bitbucket.RepositoryBranchOptions) (*bitbucket.RepositoryBranches, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", opt)
	ret0, _ := ret[0].(*bitbucket.RepositoryBranches)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockrepositoryMockRecorder) ListBranches(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*Mockrepository)(nil).ListBranches), opt)
}

// ListDefaultReviewers mocks base method.
func (m *Mockrepository) ListDefaultReviewers(opt bitbucket.RepositoryOptions) (*bitbucket.DefaultReviewers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefaultReviewers", opt)
	ret0, _ := ret[0].(*bitbucket.DefaultReviewers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefaultReviewers indicates an expected call of ListDefaultReviewers.
func (mr *MockrepositoryMockRecorder) ListDefaultReviewers(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefaultReviewers", reflect.TypeOf((*Mockrepository)(nil).ListDefaultReviewers), opt)
}

// ListDeploymentVariables mocks base method.
func (m *Mockrepository) ListDeploymentVariables(opt bitbucket.RepositoryDeploymentVariablesOptions) (*bitbucket.DeploymentVariables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeploymentVariables", opt)
	ret0, _ := ret[0].(*bitbucket.DeploymentVariables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeploymentVariables indicates an expected call of ListDeploymentVariables.
func (mr *MockrepositoryMockRecorder) ListDeploymentVariables(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeploymentVariables", reflect.TypeOf((*Mockrepository)(nil).ListDeploymentVariables), opt)
}

// ListEnvironments mocks base method.
func (m *Mockrepository) ListEnvironments(opt bitbucket.RepositoryEnvironmentsOptions) (*bitbucket.Environments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironments", opt)
	ret0, _ := ret[0].(*bitbucket.Environments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnvironments indicates an expected call of ListEnvironments.
func (mr *MockrepositoryMockRecorder) ListEnvironments(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironments", reflect.TypeOf((*Mockrepository)(nil).ListEnvironments), opt)
}

// ListFiles mocks base method.
func (m *Mockrepository) ListFiles(opt bitbucket.RepositoryFilesOptions) (*[]bitbucket.RepositoryFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", opt)
	ret0, _ := ret[0].(*[]bitbucket.RepositoryFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockrepositoryMockRecorder) ListFiles(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*Mockrepository)(nil).ListFiles), opt)
}

// ListForks mocks base method.
func (m *Mockrepository) ListForks(opt bitbucket.RepositoryOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForks", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForks indicates an expected call of ListForks.
func (mr *MockrepositoryMockRecorder) ListForks(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForks", reflect.TypeOf((*Mockrepository)(nil).ListForks), opt)
}

// ListPipelineVariables mocks base method.
func (m *Mockrepository) ListPipelineVariables(opt bitbucket.RepositoryPipelineVariablesOptions) (*bitbucket.PipelineVariables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelineVariables", opt)
	ret0, _ := ret[0].(*bitbucket.PipelineVariables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPipelineVariables indicates an expected call of ListPipelineVariables.
func (mr *MockrepositoryMockRecorder) ListPipelineVariables(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelineVariables", reflect.TypeOf((*Mockrepository)(nil).ListPipelineVariables), opt)
}

// ListWatchers mocks base method.
func (m *Mockrepository) ListWatchers(opt bitbucket.RepositoryOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWatchers", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWatchers indicates an expected call of ListWatchers.
func (mr *MockrepositoryMockRecorder) ListWatchers(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWatchers", reflect.TypeOf((*Mockrepository)(nil).ListWatchers), opt)
}

// UpdateDeploymentVariable mocks base method.
func (m *Mockrepository) UpdateDeploymentVariable(opt bitbucket.RepositoryDeploymentVariableOptions) (*bitbucket.DeploymentVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeploymentVariable", opt)
	ret0, _ := ret[0].(*bitbucket.DeploymentVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeploymentVariable indicates an expected call of UpdateDeploymentVariable.
func (mr *MockrepositoryMockRecorder) UpdateDeploymentVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeploymentVariable", reflect.TypeOf((*Mockrepository)(nil).UpdateDeploymentVariable), opt)
}

// UpdatePipelineBuildNumber mocks base method.
func (m *Mockrepository) UpdatePipelineBuildNumber(opt bitbucket.RepositoryPipelineBuildNumberOptions) (*bitbucket.PipelineBuildNumber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineBuildNumber", opt)
	ret0, _ := ret[0].(*bitbucket.PipelineBuildNumber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelineBuildNumber indicates an expected call of UpdatePipelineBuildNumber.
func (mr *MockrepositoryMockRecorder) UpdatePipelineBuildNumber(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineBuildNumber", reflect.TypeOf((*Mockrepository)(nil).UpdatePipelineBuildNumber), opt)
}

// UpdatePipelineConfig mocks base method.
func (m *Mockrepository) UpdatePipelineConfig(opt bitbucket.RepositoryPipelineOptions) (*bitbucket.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineConfig", opt)
	ret0, _ := ret[0].(*bitbucket.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelineConfig indicates an expected call of UpdatePipelineConfig.
func (mr *MockrepositoryMockRecorder) UpdatePipelineConfig(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineConfig", reflect.TypeOf((*Mockrepository)(nil).UpdatePipelineConfig), opt)
}

// UpdatePipelineVariable mocks base method.
func (m *Mockrepository) UpdatePipelineVariable(opt bitbucket.RepositoryPipelineVariableOptions) (*bitbucket.PipelineVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineVariable", opt)
	ret0, _ := ret[0].(*bitbucket.PipelineVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelineVariable indicates an expected call of UpdatePipelineVariable.
func (mr *MockrepositoryMockRecorder) UpdatePipelineVariable(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineVariable", reflect.TypeOf((*Mockrepository)(nil).UpdatePipelineVariable), opt)
}

// Mockrepositories is a mock of repositories interface.
type Mockrepositories struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoriesMockRecorder
	isgomock struct{}
}

// MockrepositoriesMockRecorder is the mock recorder for Mockrepositories.
type MockrepositoriesMockRecorder struct {
	mock *Mockrepositories
}

// NewMockrepositories creates a new mock instance.
func NewMockrepositories(ctrl *gomock.Controller) *Mockrepositories {
	mock := &Mockrepositories{ctrl: ctrl}
	mock.recorder = &MockrepositoriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepositories) EXPECT() *MockrepositoriesMockRecorder {
	return m.recorder
}

// ListForAccount mocks base method.
func (m *Mockrepositories) ListForAccount(opt bitbucket.RepositoriesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForAccount", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForAccount indicates an expected call of ListForAccount.
func (mr *MockrepositoriesMockRecorder) ListForAccount(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForAccount", reflect.TypeOf((*Mockrepositories)(nil).ListForAccount), opt)
}

// ListForTeam mocks base method.
func (m *Mockrepositories) ListForTeam(opt bitbucket.RepositoriesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForTeam", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForTeam indicates an expected call of ListForTeam.
func (mr *MockrepositoriesMockRecorder) ListForTeam(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForTeam", reflect.TypeOf((*Mockrepositories)(nil).ListForTeam), opt)
}

// ListProject mocks base method.
func (m *Mockrepositories) ListProject(opt bitbucket.RepositoriesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProject", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProject indicates an expected call of ListProject.
func (mr *MockrepositoriesMockRecorder) ListProject(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProject", reflect.TypeOf((*Mockrepositories)(nil).ListProject), opt)
}

// ListPublic mocks base method.
func (m *Mockrepositories) ListPublic() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublic")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublic indicates an expected call of ListPublic.
func (mr *MockrepositoriesMockRecorder) ListPublic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublic", reflect.TypeOf((*Mockrepositories)(nil).ListPublic))
}

// Mockcommits is a mock of commits interface.
type Mockcommits struct {
	ctrl     *gomock.Controller
	recorder *MockcommitsMockRecorder
	isgomock struct{}
}

// MockcommitsMockRecorder is the mock recorder for Mockcommits.
type MockcommitsMockRecorder struct {
	mock *Mockcommits
}

// NewMockcommits creates a new mock instance.
func NewMockcommits(ctrl *gomock.Controller) *Mockcommits {
	mock := &Mockcommits{ctrl: ctrl}
	mock.recorder = &MockcommitsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcommits) EXPECT() *MockcommitsMockRecorder {
	return m.recorder
}

// CreateCommitStatus mocks base method.
func (m *Mockcommits) CreateCommitStatus(cmo bitbucket.CommitsOptions, cso bitbucket.CommitStatusOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommitStatus", cmo, cso)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommitStatus indicates an expected call of CreateCommitStatus.
func (mr *MockcommitsMockRecorder) CreateCommitStatus(cmo, cso any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommitStatus", reflect.TypeOf((*Mockcommits)(nil).CreateCommitStatus), cmo, cso)
}

// GetCommit mocks base method.
func (m *Mockcommits) GetCommit(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommit", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommit indicates an expected call of GetCommit.
func (mr *MockcommitsMockRecorder) GetCommit(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommit", reflect.TypeOf((*Mockcommits)(nil).GetCommit), opt)
}

// GetCommitComment mocks base method.
func (m *Mockcommits) GetCommitComment(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitComment", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitComment indicates an expected call of GetCommitComment.
func (mr *MockcommitsMockRecorder) GetCommitComment(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitComment", reflect.TypeOf((*Mockcommits)(nil).GetCommitComment), opt)
}

// GetCommitComments mocks base method.
func (m *Mockcommits) GetCommitComments(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitComments", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitComments indicates an expected call of GetCommitComments.
func (mr *MockcommitsMockRecorder) GetCommitComments(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitComments", reflect.TypeOf((*Mockcommits)(nil).GetCommitComments), opt)
}

// GetCommitStatus mocks base method.
func (m *Mockcommits) GetCommitStatus(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitStatus", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitStatus indicates an expected call of GetCommitStatus.
func (mr *MockcommitsMockRecorder) GetCommitStatus(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitStatus", reflect.TypeOf((*Mockcommits)(nil).GetCommitStatus), opt)
}

// GetCommits mocks base method.
func (m *Mockcommits) GetCommits(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommits", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommits indicates an expected call of GetCommits.
func (mr *MockcommitsMockRecorder) GetCommits(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommits", reflect.TypeOf((*Mockcommits)(nil).GetCommits), opt)
}

// GiveApprove mocks base method.
func (m *Mockcommits) GiveApprove(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GiveApprove", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GiveApprove indicates an expected call of GiveApprove.
func (mr *MockcommitsMockRecorder) GiveApprove(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveApprove", reflect.TypeOf((*Mockcommits)(nil).GiveApprove), opt)
}

// RemoveApprove mocks base method.
func (m *Mockcommits) RemoveApprove(opt bitbucket.CommitsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveApprove", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveApprove indicates an expected call of RemoveApprove.
func (mr *MockcommitsMockRecorder) RemoveApprove(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveApprove", reflect.TypeOf((*Mockcommits)(nil).RemoveApprove), opt)
}

// Mockbranchrestrictions is a mock of branchrestrictions interface.
type Mockbranchrestrictions struct {
	ctrl     *gomock.Controller
	recorder *MockbranchrestrictionsMockRecorder
	isgomock struct{}
}

// MockbranchrestrictionsMockRecorder is the mock recorder for Mockbranchrestrictions.
type MockbranchrestrictionsMockRecorder struct {
	mock *Mockbranchrestrictions
}

// NewMockbranchrestrictions creates a new mock instance.
func NewMockbranchrestrictions(ctrl *gomock.Controller) *Mockbranchrestrictions {
	mock := &Mockbranchrestrictions{ctrl: ctrl}
	mock.recorder = &MockbranchrestrictionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockbranchrestrictions) EXPECT() *MockbranchrestrictionsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockbranchrestrictions) Create(opt bitbucket.BranchRestrictionsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockbranchrestrictionsMockRecorder) Create(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockbranchrestrictions)(nil).Create), opt)
}

// Delete mocks base method.
func (m *Mockbranchrestrictions) Delete(opt bitbucket.BranchRestrictionsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockbranchrestrictionsMockRecorder) Delete(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockbranchrestrictions)(nil).Delete), opt)
}

// Get mocks base method.
func (m *Mockbranchrestrictions) Get(opt bitbucket.BranchRestrictionsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockbranchrestrictionsMockRecorder) Get(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockbranchrestrictions)(nil).Get), opt)
}

// Gets mocks base method.
func (m *Mockbranchrestrictions) Gets(opt bitbucket.BranchRestrictionsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gets", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gets indicates an expected call of Gets.
func (mr *MockbranchrestrictionsMockRecorder) Gets(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gets", reflect.TypeOf((*Mockbranchrestrictions)(nil).Gets), opt)
}

// Update mocks base method.
func (m *Mockbranchrestrictions) Update(opt bitbucket.BranchRestrictionsOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockbranchrestrictionsMockRecorder) Update(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockbranchrestrictions)(nil).Update), opt)
}

// Mockdiff is a mock of diff interface.
type Mockdiff struct {
	ctrl     *gomock.Controller
	recorder *MockdiffMockRecorder
	isgomock struct{}
}

// MockdiffMockRecorder is the mock recorder for Mockdiff.
type MockdiffMockRecorder struct {
	mock *Mockdiff
}

// NewMockdiff creates a new mock instance.
func NewMockdiff(ctrl *gomock.Controller) *Mockdiff {
	mock := &Mockdiff{ctrl: ctrl}
	mock.recorder = &MockdiffMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdiff) EXPECT() *MockdiffMockRecorder {
	return m.recorder
}

// GetDiff mocks base method.
func (m *Mockdiff) GetDiff(opt bitbucket.DiffOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiff", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiff indicates an expected call of GetDiff.
func (mr *MockdiffMockRecorder) GetDiff(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiff", reflect.TypeOf((*Mockdiff)(nil).GetDiff), opt)
}

// GetPatch mocks base method.
func (m *Mockdiff) GetPatch(opt bitbucket.DiffOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatch", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatch indicates an expected call of GetPatch.
func (mr *MockdiffMockRecorder) GetPatch(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatch", reflect.TypeOf((*Mockdiff)(nil).GetPatch), opt)
}

// Mockwebhooks is a mock of webhooks interface.
type Mockwebhooks struct {
	ctrl     *gomock.Controller
	recorder *MockwebhooksMockRecorder
	isgomock struct{}
}

// MockwebhooksMockRecorder is the mock recorder for Mockwebhooks.
type MockwebhooksMockRecorder struct {
	mock *Mockwebhooks
}

// NewMockwebhooks creates a new mock instance.
func NewMockwebhooks(ctrl *gomock.Controller) *Mockwebhooks {
	mock := &Mockwebhooks{ctrl: ctrl}
	mock.recorder = &MockwebhooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwebhooks) EXPECT() *MockwebhooksMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockwebhooks) Create(opt bitbucket.WebhooksOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockwebhooksMockRecorder) Create(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockwebhooks)(nil).Create), opt)
}

// Delete mocks base method.
func (m *Mockwebhooks) Delete(opt bitbucket.WebhooksOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockwebhooksMockRecorder) Delete(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockwebhooks)(nil).Delete), opt)
}

// Get mocks base method.
func (m *Mockwebhooks) Get(opt bitbucket.WebhooksOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockwebhooksMockRecorder) Get(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockwebhooks)(nil).Get), opt)
}

// Gets mocks base method.
func (m *Mockwebhooks) Gets(opt bitbucket.WebhooksOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gets", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gets indicates an expected call of Gets.
func (mr *MockwebhooksMockRecorder) Gets(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gets", reflect.TypeOf((*Mockwebhooks)(nil).Gets), opt)
}

// Update mocks base method.
func (m *Mockwebhooks) Update(opt bitbucket.WebhooksOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", opt)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockwebhooksMockRecorder) Update(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockwebhooks)(nil).Update), opt)
}

// Mockteams is a mock of teams interface.
type Mockteams struct {
	ctrl     *gomock.Controller
	recorder *MockteamsMockRecorder
	isgomock struct{}
}

// MockteamsMockRecorder is the mock recorder for Mockteams.
type MockteamsMockRecorder struct {
	mock *Mockteams
}

// NewMockteams creates a new mock instance.
func NewMockteams(ctrl *gomock.Controller) *Mockteams {
	mock := &Mockteams{ctrl: ctrl}
	mock.recorder = &MockteamsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockteams) EXPECT() *MockteamsMockRecorder {
	return m.recorder
}

// Followers mocks base method.
func (m *Mockteams) Followers(teamname string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Followers", teamname)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Followers indicates an expected call of Followers.
func (mr *MockteamsMockRecorder) Followers(teamname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Followers", reflect.TypeOf((*Mockteams)(nil).Followers), teamname)
}

// Following mocks base method.
func (m *Mockteams) Following(teamname string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Following", teamname)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Following indicates an expected call of Following.
func (mr *MockteamsMockRecorder) Following(teamname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Following", reflect.TypeOf((*Mockteams)(nil).Following), teamname)
}

// List mocks base method.
func (m *Mockteams) List(role string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", role)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockteamsMockRecorder) List(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockteams)(nil).List), role)
}

// Members mocks base method.
func (m *Mockteams) Members(teamname string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members", teamname)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Members indicates an expected call of Members.
func (mr *MockteamsMockRecorder) Members(teamname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*Mockteams)(nil).Members), teamname)
}

// Profile mocks base method.
func (m *Mockteams) Profile(teamname string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", teamname)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockteamsMockRecorder) Profile(teamname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*Mockteams)(nil).Profile), teamname)
}

// Projects mocks base method.
func (m *Mockteams) Projects(teamname string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Projects", teamname)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Projects indicates an expected call of Projects.
func (mr *MockteamsMockRecorder) Projects(teamname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Projects", reflect.TypeOf((*Mockteams)(nil).Projects), teamname)
}

// Repositories mocks base method.
func (m *Mockteams) Repositories(teamname string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repositories", teamname)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repositories indicates an expected call of Repositories.
func (mr *MockteamsMockRecorder) Repositories(teamname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repositories", reflect.TypeOf((*Mockteams)(nil).Repositories), teamname)
}

// Mockpipelines is a mock of pipelines interface.
type Mockpipelines struct {
	ctrl     *gomock.Controller
	recorder *MockpipelinesMockRecorder
	isgomock struct{}
}

// MockpipelinesMockRecorder is the mock recorder for Mockpipelines.
type MockpipelinesMockRecorder struct {
	mock *Mockpipelines
}

// NewMockpipelines creates a new mock instance.
func NewMockpipelines(ctrl *gomock.Controller) *Mockpipelines {
	mock := &Mockpipelines{ctrl: ctrl}
	mock.recorder = &MockpipelinesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpipelines) EXPECT() *MockpipelinesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *Mockpipelines) Get(po *bitbucket.PipelinesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", po)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockpipelinesMockRecorder) Get(po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockpipelines)(nil).Get), po)
}

// GetLog mocks base method.
func (m *Mockpipelines) GetLog(po *bitbucket.PipelinesOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", po)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLog indicates an expected call of GetLog.
func (mr *MockpipelinesMockRecorder) GetLog(po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*Mockpipelines)(nil).GetLog), po)
}

// GetStep mocks base method.
func (m *Mockpipelines) GetStep(po *bitbucket.PipelinesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStep", po)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStep indicates an expected call of GetStep.
func (mr *MockpipelinesMockRecorder) GetStep(po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStep", reflect.TypeOf((*Mockpipelines)(nil).GetStep), po)
}

// List mocks base method.
func (m *Mockpipelines) List(po *bitbucket.PipelinesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", po)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockpipelinesMockRecorder) List(po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockpipelines)(nil).List), po)
}

// ListSteps mocks base method.
func (m *Mockpipelines) ListSteps(po *bitbucket.PipelinesOptions) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSteps", po)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSteps indicates an expected call of ListSteps.
func (mr *MockpipelinesMockRecorder) ListSteps(po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSteps", reflect.TypeOf((*Mockpipelines)(nil).ListSteps), po)
}
